source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'YTKNetwork'

pod 'SDWebImage', '~>3.7'

pod 'SVProgressHUD'

pod 'MJRefresh'

pod 'Bugly'

pod 'RPJSONValidator', '~> 0.2.0'

pod 'TTTAttributedLabel'
